---
version: "3.0"
services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Scx1q
      - META_DESCRIPTION=Coder | Student | Australian
      - META_AUTHOR=Scx1q
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Scx1q
      - OG_TITLE=Scx1q
      - OG_DESCRIPTION=The home of Scx1q
      - OG_URL=https://technotim.live
      - OG_IMAGE=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
      - AVATAR_2X_URL=https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_400x400.jpg
      - AVATAR_ALT=Techno Tim Profile Pic
      - NAME=Scx1q
      - BIO=Hey! Just a place where you can connect with me!
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=DISCORD,SPOTIFY,SNAPCHAT,GITHUB,TIKTOK,EMAIL
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_ICON=fas file-alt,fas fa-cog
      - GITHUB=https://github.com/Scx1q
      - SPOTIFY=https://open.spotify.com/user/mwg60wlb7wvwqlxm9xpjfro41?si=ee0aae571c894993
      #- TWITTER=https://l.technotim.live/twitter
      #- INSTAGRAM=https://l.technotim.live/instagram
      #- YOUTUBE=https://l.technotim.live/subscribe
      #- TWITCH=https://l.technotim.live/twitch
      - DISCORD=https://discord.gg/7faQETAPgv
      - TIKTOK=https://www.tiktok.com/@scx1q
      - SNAPCHAT=https://www.snapchat.com/add/lostinlifelol
      - EMAIL=scx1qbusiness@gmail.com
      #- FACEBOOK=https://l.technotim.live/facebook
      #- PATREON=https://l.technotim.live/patreon
      - FOOTER=Scx1q © 2022
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
